//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpenseWebApp.Utilities.ResourceFiles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceFile {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceFile() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExpenseWebApp.Utilities.ResourceFiles.ResourceFile", typeof(ResourceFile).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Been Submitted for Approval.
        /// </summary>
        public static string ApproverMailBody {
            get {
                return ResourceManager.GetString("ApproverMailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Approval Request.
        /// </summary>
        public static string ApproverMailSubject {
            get {
                return ResourceManager.GetString("ApproverMailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAD.
        /// </summary>
        public static string CashAdvanceForm {
            get {
                return ResourceManager.GetString("CashAdvanceForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RET.
        /// </summary>
        public static string CashAdvanceRetirementForm {
            get {
                return ResourceManager.GetString("CashAdvanceRetirementForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Been Approved and awaits disbursement.
        /// </summary>
        public static string DisburserMailBody {
            get {
                return ResourceManager.GetString("DisburserMailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Disbursement Request.
        /// </summary>
        public static string DisburserMailSubject {
            get {
                return ResourceManager.GetString("DisburserMailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expense doesn&apos;t exist.
        /// </summary>
        public static string ExpenseDetailNotFound {
            get {
                return ResourceManager.GetString("ExpenseDetailNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXP.
        /// </summary>
        public static string ExpenseForm {
            get {
                return ResourceManager.GetString("ExpenseForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense forms deleted successfully..
        /// </summary>
        public static string ExpenseFormsDeleted {
            get {
                return ResourceManager.GetString("ExpenseFormsDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email sending failed but user will get notified when they log in..
        /// </summary>
        public static string FailedToSendEmail {
            get {
                return ResourceManager.GetString("FailedToSendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field cannot be empty..
        /// </summary>
        public static string FieldNotEmpty {
            get {
                return ResourceManager.GetString("FieldNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data for the specified form type exists.
        /// </summary>
        public static string FormCountDataNotFound {
            get {
                return ResourceManager.GetString("FormCountDataNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The form&apos;s count was updated successfully.
        /// </summary>
        public static string FormCountUpdate {
            get {
                return ResourceManager.GetString("FormCountUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The form(s) with the specified form ID doesn&apos;t exists..
        /// </summary>
        public static string FormNotFound {
            get {
                return ResourceManager.GetString("FormNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The form&apos;s status wasn&apos;t updated successfully..
        /// </summary>
        public static string FormUpdateFailed {
            get {
                return ResourceManager.GetString("FormUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The form&apos;s status was updated successfully.
        /// </summary>
        public static string FormUpdateSuccess {
            get {
                return ResourceManager.GetString("FormUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must provide a note when requesting for further information.
        /// </summary>
        public static string FurtherInfoNoteRequired {
            get {
                return ResourceManager.GetString("FurtherInfoNoteRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Must be greater than 0.
        /// </summary>
        public static string InvalidAmount {
            get {
                return ResourceManager.GetString("InvalidAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid data, Pls enter a valid data.
        /// </summary>
        public static string InvalidData {
            get {
                return ResourceManager.GetString("InvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid date.
        /// </summary>
        public static string InvalidDate {
            get {
                return ResourceManager.GetString("InvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Form status.
        /// </summary>
        public static string InvalidStatus {
            get {
                return ResourceManager.GetString("InvalidStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No form with specified status exist..
        /// </summary>
        public static string NotExisting {
            get {
                return ResourceManager.GetString("NotExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field cannot be null.
        /// </summary>
        public static string NotNull {
            get {
                return ResourceManager.GetString("NotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form has been process by an approver.
        /// </summary>
        public static string ProcessedForm {
            get {
                return ResourceManager.GetString("ProcessedForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must provide a note when Rejecting.
        /// </summary>
        public static string RejectionNoteRequired {
            get {
                return ResourceManager.GetString("RejectionNoteRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form Status Update.
        /// </summary>
        public static string RequestorMailSubject {
            get {
                return ResourceManager.GetString("RequestorMailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The status doesn&apos;t exist.
        /// </summary>
        public static string StatusNotFound {
            get {
                return ResourceManager.GetString("StatusNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Been Submitted for Approval.
        /// </summary>
        public static string SubmittedForApproval {
            get {
                return ResourceManager.GetString("SubmittedForApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful..
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsuccessful.
        /// </summary>
        public static string Unsuccessful {
            get {
                return ResourceManager.GetString("Unsuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User&apos;s Form(s) Not Found.
        /// </summary>
        public static string UserFormNotFound {
            get {
                return ResourceManager.GetString("UserFormNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record does not exist.
        /// </summary>
        public static string UsersNotFound {
            get {
                return ResourceManager.GetString("UsersNotFound", resourceCulture);
            }
        }
    }
}
